
# This YAML file specifies the deployment configuration for the Render platform.
# It defines the environment type, build commands, startup commands, hosting plan,
# and environment variables sourced from Render's dashboard for secure and easy deployment.

services:
  - type: web
    name: ITechProject
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn srcwebproject.wsgi:application --log-file -"
    plan: free
    envVars:
      - key: SECRET_KEY
        fromEnv: SECRET_KEY
      - key: DEBUG
        fromEnv: DEBUG
      - key: ALLOWED_HOSTS
        fromEnv: ALLOWED_HOSTS
      - key: EMAIL_HOST
        fromEnv: EMAIL_HOST
      - key: EMAIL_PORT
        fromEnv: EMAIL_PORT
      - key: EMAIL_USE_TLS
        fromEnv: EMAIL_USE_TLS
      - key: EMAIL_HOST_USER
        fromEnv: EMAIL_HOST_USER
      - key: EMAIL_HOST_PASSWORD
        fromEnv: EMAIL_HOST_PASSWORD
      - key: DEFAULT_FROM_EMAIL
        fromEnv: DEFAULT_FROM_EMAIL